# Generated by Django 3.2.13 on 2022-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email_vertificated',
            field=models.BooleanField(default=False),
        ),
    ]
